### PR TITLE
Add csprng.d.ts

### PR DESCRIPTION
**Pull request by winksaville**
Bump version and add types to package.json

### CODE REVIEW

**Comment by winksaville** [comment]
@jcoglan, I also created [test-node-csprng](https://github.com/winksaville/test-node-csprng) if you'd like I can create another PR or add it to this one.

**Comment by jcoglan** [comment]
Hi @winksaville, thanks for the PR but I tend not to accept TypeScript-related metadata into my projects, since I'm not a TypeScript user and so will probably not do a good job of maintaining any such code.

I would prefer for TypeScript users to take my plain JavaScript code and package it for TypeScript, in much the same way that Linux distros take upstream software and package it for their users. Is there a means of doing that for TypeScript?

**Comment by winksaville** [comment]
There is the DefinitelyTyped repo that the csprng.d.ts can go into, but it's harder to keep in sync. If we put in your repo it's all together and easy to manage. As you can see the only thing in csprng.d.ts is the signature and you can ignore it completely from JavaScript.

**Comment by winksaville** [comment]
I'm new to web development, I've done mostly C/C++/Java stuff so I like strong type checking and hence TypeScript feels more comfortable. If I may ask, why are you shying away from TypeScript?

**Comment by winksaville** [comment]
I've added [csprng.d.ts to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15178), so I'm closing this. Please do consider adding csrpng.d.ts to your repository in the future. And I'd still like your opinion on TypeScript.

**Pull request closed without merging**
